# Project
project: Chef-OpenStack
lead: "Get the efficiency, scalability, and control that every private cloud needs."
public_url: http://softlayer.github.io/chef-openstack

# GitHub
repo: http://github.com/softlayer/chef-openstack
fork: http://github.com/softlayer/chef-openstack/fork
star: http://github.com/softlayer/chef-openstack/stargazers
open_issues: http://github.com/softlayer/chef-openstack/issues?milestone=1;state=open
closed_issues: http://github.com/softlayer/chef-openstack/issues?milestone=1;state=closed
milestones: http://github.com/softlayer/chef-openstack/issues/milestones?state=open
commits: http://github.com/softlayer/chef-openstack/commits
contributors: https://github.com/softlayer/chef-openstack/graphs/contributors

# Company
www: http://www.softlayer.com
license: https://github.com/softlayer/chef-openstack/blob/Havana/LICENSE
sldn: http://sldn.softlayer.com
kb: http://knowledgelayer.softlayer.com
blog: http://blog.softlayer.com

# Social
github: http://github.com/softlayer
twitter: http://twitter.com/softlayerdevs

# Server
permalink: pretty
exclude: [".gitignore", "README.md", "LICENSE"]
pygments: true
safe: false

# Google Analytics
ga_tracking_id: UA-40037365-1
ga_tracking_domain: softlayer.github.io