# Project
project: Chef-OpenStack
lead: "Get the efficiency, scalability and control that every private cloud needs"
version_havana: 0.3.3
version_grizzly: 0.2.0

# Links
repo: http://github.com/softlayer/chef-openstack
www: http://www.softlayer.com
sldn: http://sldn.softlayer.com
portal: http://manage.softlayer.com
twitter: http://twitter.com/softlayerdevs

# Server
baseurl: http://softlayer.github.io/chef-openstack
permalink: pretty
exclude: [".gitignore", "LICENSE", "README.md"]
