# Project Name
project: Chef-OpenStack
tagline: "Grow your possibilities"
lead: "Get the efficiency, scalability and control that every private cloud needs"

# Versioning
version_havana: 0.3.3
version_grizzly: 0.2.0

# GitHub Links
repo: http://github.com/softlayer/chef-openstack
license: http://github.com/softlayer/chef-openstack/blob/Havana/LICENSE
open_issues: http://github.com/softlayer/chef-openstack/issues?milestone=1;state=open
closed_issues: http://github.com/softlayer/chef-openstack/issues?milestone=1;state=closed

#Company Links
www: http://www.softlayer.com
sldn: http://sldn.softlayer.com
portal: http://manage.softlayer.com
twitter: http://twitter.com/softlayerdevs

# Server
permalink: pretty
exclude: [".gitignore", "LICENSE", "README.md", "TODO.md", "humans.txt"]