# Project
project: Chef-OpenStack
lead: "Get the efficiency, scalability and control that every private cloud needs"

# Links
repo: http://github.com/softlayer/chef-openstack
www: http://www.softlayer.com
sldn: http://sldn.softlayer.com
portal: http://manage.softlayer.com
twitter: http://twitter.com/softlayerdev

# Server
permalink: pretty
exclude: [".gitignore", "LICENSE", "README.md"]