# -- START EDITING -- #

# Project Info
project: Chef-OpenStack
lead: "Grow your possibilities. Get the flexibility, control, efficiency, and scalability that every private cloud solution needs."

# GitHub Links
repo: "http://github.com/softlayer/chef-openstack"
star: "http://ghbtns.com/github-btn.html?user=softlayer&amp;repo=chef-openstack&amp;type=watch&amp;count=true"
fork: "http://ghbtns.com/github-btn.html?user=softlayer&amp;repo=chef-openstack&amp;type=fork&amp;count=true"

# -- STOP EDITING -- #

# Dependencies
pygments: true
markdown: RedCloth
textile_ext: textile

# Server
domain: softlayer.github.com

# Settings
analytics: UA-40037365-1
permalink: pretty

# SL Websites
www: http://www.softlayer.com
sldn: http://sldn.softlayer.com
portal: http://manage.softlayer.com
twitter: http://twitter.com/SoftLayerDev